src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Catname = null;

    #[ORM\OneToMany(mappedBy: 'category', targetEntity: Product::class)]
    private Collection $Products;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logo = null;

    public function __construct()
    {
        $this->Products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCatname(): ?string
    {
        return $this->Catname;
    }

    public function setCatname(?string $Catname): static
    {
        $this->Catname = $Catname;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->Products;
    }

    public function addProduct(Product $product): static
    {
        if (!$this->Products->contains($product)) {
            $this->Products->add($product);
            $product->setCategory($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): static
    {
        if ($this->Products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getCategory() === $this) {
                $product->setCategory(null);
            }
        }

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): static
    {
        $this->logo = $logo;

        return $this;
    }
}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use App\Entity\Address;
use App\Entity\Category;
use App\Entity\Order;
use App\Entity\OrderItem;
use App\Entity\Product;
use App\Entity\ProductImage;
use App\Entity\PurchaseOrder;
use App\Entity\User;
use App\Form\AddressType;
use App\Form\CartType;
use App\Form\CategoryType;
use App\Form\ProductType;
use App\Manager\CartManager;
use App\Repository\CategoryRepository;
use App\Repository\ProductRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\HttpFoundation\JsonResponse;
use App\Repository\PurchaseOrderRepository;
use App\Repository\AddressRepository;
use Symfony\Component\String\Slugger\SluggerInterface;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;


class DashboardController  extends AbstractController
{
    private $entityManager;
    private $security;

    public function __construct(EntityManagerInterface $entityManager, Security $security)
    {
        $this->entityManager = $entityManager;
        $this->security = $security;
    }

    #[Route('/dashboard ', name: 'dashboard_index')]
    #[IsGranted('ROLE_ADMIN')]
    public function indexDashboard(ManagerRegistry $doctrine,Request $request, CartManager $cartManager, PurchaseOrderRepository $orderRepository,
                                   CategoryRepository $categoryRepository, ProductRepository $productRepository, UserRepository $userRepository,
                                   EntityManagerInterface $entityManager): Response
    {
        $products = $doctrine->getRepository(Product::class)->findAll();
        $categories = $doctrine->getRepository(Category::class)->findAll();
        $cart = $cartManager->getCurrentCart();

        // Lấy tổng số đơn hàng từ database
        $totalOrders = $orderRepository->countAllOrders();
        // Lấy tổng số đơn hàng có status = 0 từ database
        $statusOrders = $orderRepository->countOrdersByStatus(0);
        $totalCategories = $categoryRepository->countAllCategories();
        $totalProducts = $productRepository->countAllProducts();
        $sumQuantityProducts = $productRepository->sumTotalQuantity();
        $totalUsers = $userRepository->countAllUsers();
        $totalSuperAdmins = $userRepository->countUsersByRole('ROLE_SUPER_ADMIN');

        $purchaseOrders = $entityManager->getRepository(PurchaseOrder::class)->findAll();
        $bestSellingProducts = [];

        // Calculate the total quantity for each product_id and unique users
        foreach ($purchaseOrders as $order) {
            $productId = $order->getProductId();
            $quantity = $order->getQuantity();
            $userId = $order->getUser();
            $image = $order->getPurchaseImage();
            $name = $order->getName();

            if (isset($bestSellingProducts[$productId])) {
                $bestSellingProducts[$productId]['quantity'] += $quantity;

                // Add the user only if it's not already in the users array for this product
                if (!in_array($userId, $bestSellingProducts[$productId]['users'], true)) {
                    $bestSellingProducts[$productId]['users'][] = $userId;
                }
            } else {
                $bestSellingProducts[$productId] = [
                    'quantity' => $quantity,
                    'users' => [$userId],
                    'image' => $image,
                    'name' => $name,
                ];
            }
        }

        return $this->render('dashboard/index.html.twig', [
            'products' => $products, 'categories'=>$categories, 'cart' => $cart, 'totalOrders' => $totalOrders, 'statusOrders' => $statusOrders,
            'totalCategories' => $totalCategories, 'totalProducts' => $totalProducts, 'sumQuantityProducts' => $sumQuantityProducts,
            'totalUsers' => $totalUsers, 'totalSuperAdmins' => $totalSuperAdmins,'bestSellingProducts' => $bestSellingProducts,
        ]);
    }



    #[Route('/dashboard/category/create', name: 'dashboard_category_create')]
    #[IsGranted('ROLE_ADMIN')]
    public function createCategoryDashboard(ManagerRegistry $doctrine, Request $request, SluggerInterface $slugger, CartManager $cartManager)
    {
        $categories = new Category();
        $form = $this->createForm(CategoryType::class, $categories);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            // upload file
            $logoImage = $form->get('logoImage')->getData();
            if ($logoImage) {
                $originalFilename = pathinfo($logoImage->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $logoImage->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $logoImage->move(
                        $this->getParameter('logoImage_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    $this->addFlash(
                        'error',
                        'Cannot upload'
                    );// ... handle exception if something happens during file upload
                }
                $categories->setLogo($newFilename);
            } else {
                $this->addFlash(
                    'error',
                    'Cannot upload'
                );// ... handle exception if something happens during file upload
            }

            $em = $doctrine->getManager();
            $em->persist($categories);
            $em->flush();

            return $this->redirectToRoute('dashboard_category_details');
        }
        return $this->renderForm('dashboard/dashboard_category_create.html.twig', ['form' => $form]);
    }
    #[Route('/dashboard/category/details', name: 'dashboard_category_details')]
    #[IsGranted('ROLE_ADMIN')]
    public function detailsCategory(ManagerRegistry $doctrine, CartManager $cartManager): Response
    {
        $categories = $doctrine->getRepository(Category::class)->findAll();

        return $this->render('dashboard/dashboard_category_details.html.twig', [
            'categories'=>$categories
        ]);
    }

    #[Route('/dashboard/category/delete/{id}', name: 'dashboard_category_delete')]
    #[IsGranted('ROLE_ADMIN')]
    public function deleteCategoryDashboard(ManagerRegistry $doctrine,$id)
    {
        $em = $doctrine->getManager();
        $categories = $em->getRepository(Category::class)->find($id);
        $em->remove($categories);
        $em->flush();

        return $this->redirectToRoute('dashboard_category_details');
    }

    #[Route('/dashboard/category/edit/{id}', name: 'dashboard_category_edit')]
    #[IsGranted('ROLE_ADMIN')]
    public function editActionDashboard(ManagerRegistry $doctrine, int $id, Request $request, SluggerInterface $slugger, CartManager $cartManager): Response
    {
        $entityManager = $doctrine->getManager();
        $categories = $entityManager->getRepository(Category::class)->find($id);
        $form = $this->createForm(CategoryType::class, $categories);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            // upload file
            $logoImage = $form->get('logoImage')->getData();
            if ($logoImage) {
                $originalFilename = pathinfo($logoImage->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $logoImage->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $logoImage->move(
                        $this->getParameter('logoImage_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    $this->addFlash(
                        'error',
                        'Cannot upload'
                    );// ... handle exception if something happens during file upload
                }
                $categories->setLogo($newFilename);
            } else {
                $this->addFlash(
                    'error',
                    'Cannot upload'
                );// ... handle exception if something happens during file upload
            }

            $em = $doctrine->getManager();
            $em->persist($categories);
            $em->flush();

            return $this->redirectToRoute('dashboard_category_details');
        }

        return $this->renderForm('dashboard/dashboard_category_edit.html.twig', ['form' => $form, 'categories' => $categories]);
    }

    #[Route('/dashboard/purchase-order', name: 'dashboard_purchase-order')]
    #[IsGranted('ROLE_ADMIN')]
    public function detailsPurchaseOrderDashboard(ManagerRegistry $doctrine, CartManager $cartManager): Response
    {
        $categories = $doctrine->getRepository(Category::class)->findAll();

templates/dashboard/base.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{{ asset ('uploads/important/favicon.webp') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
<div class="container-fluid p-0" style="background: #f1f5f9">
    <div class="row">
        <div class="col-md-6 col-xxl-2 text-white full-height" style="background: #FFFFFF">
            <!-- Sidebar content -->
            <a href="{{ path('product_list') }}">
            <div style="height: 100px; display: flex; flex-direction: column; align-items: center; justify-content: center;">
                <img src="{{ asset('uploads/image/logo.webp')}}" alt="Logo GearVN" style="width:180px;">
            </div>
            </a>
            <br>

            <a href="{{ path('dashboard_index') }}">
                <div style="margin-left: 20px"><b>Dashboard</b></div>
            </a>

            <br>
            <div style="margin-left: 20px; color: rgba(115,115,116,0.66);"><b>ORDERS MANAGEMENT</b></div>
            <br>

            <a href="{{ path('dashboard_purchase-order') }}">
                <div style="margin-left: 20px; height: 40px"><b>Accept Orders</b></div>
            </a>
            <a href="{{ path('all-orders') }}">
                <div style="margin-left: 20px; height: 40px"><b>All orders</b></div>
            </a>


            <br>
            <div style="margin-left: 20px; color: rgba(115,115,116,0.66);"><b>CATEGORYS MANAGEMENT</b></div>
            <br>
            <a href="{{ path('dashboard_category_create') }}">
                <div style="margin-left: 20px; height: 40px"><b>Add Category</b></div>
            </a>
            <a href="{{ path('dashboard_category_details') }}">
                <div style="margin-left: 20px; height: 40px"><b>Category List</b></div>
            </a>

            <br>
            <div style="margin-left: 20px; color: rgba(115,115,116,0.66);"><b>PRODUCTS MANAGEMENT</b></div>
            <br>
            <a href="{{ path('dashboard_product_create') }}">
                <div style="margin-left: 20px; height: 40px"><b>Add Product</b></div>
            </a>
            <a href="{{ path('dashboard_product_list') }}">
                <div style="margin-left: 20px; height: 40px"><b>Product List</b></div>
            </a>

            <br>
            <div style="margin-left: 20px; color: rgba(115,115,116,0.66);"><b>USERS MANAGEMENT</b></div>
            <br>
            <a href="{{ path('dashboard_user') }}">
                <div style="margin-left: 20px; height: 40px"><b>Grant permissions to users</b></div>
            </a>
        </div>
        <div class="col-md-6 col-xxl-10 overflow-auto" style="margin-left: 16.6667%; height: 100vh;">
            <!-- Content will be included here from child pages -->
            {% block content %}{% endblock %}
        </div>
    </div>
</div>

</body>
<style>
    .full-height {
        height: 100vh;
        position: fixed;
        top: 0;
        left: 0;
        bottom: 0;
        z-index: 1;
        overflow-y: auto;
    }

    .overflow-auto {
        overflow-y: auto;
    }
    a {
        text-decoration: none;
        color: #8e8f93;
        transition-duration: 0.5s;
    }
    a:hover {

        color: red;
    }
</style>
</html>

templates/dashboard/dashboard_all-orders.html.twig
{% extends 'dashboard/base.html.twig' %}

{% block content %}
<br>
<div class="container-fluid">
    <table class="table">
        <thead>
        <tr>
            <th class="text-center ">ID Order</th>
            <th class="text-center ">Product</th>
            <th class="text-center "></th>
            <th class="text-center ">Status</th>
            <th class="text-center ">Quantity</th>
            <th class="text-center ">Price</th>
            <th class="text-center ">User Name</th>
            <th class="text-center ">Phone</th>
            <th class="text-center ">Address</th>
            <th class="text-center ">Order Date</th>
        </tr>
        </thead>
        <tbody>
        {% for purchaseOrder in purchaseOrders %}
            {% for address in addresses %}
                {% if address.user.id == purchaseOrder.getUser().getId() %}
                    <tr>
                        <td>#{{ purchaseOrder.getIdOrder() }}</td>
                        <td>
                            <img src="{{ asset('uploads/image/' ~ purchaseOrder.getPurchaseImage()) }}" class="card-img-top" style="width: 100px" alt="Product Image">
                        </td>
                        <td>
                            {{ purchaseOrder.getName() }}
                        </td>
                        <td>
                            {% if purchaseOrder.getStatus() == 0 %}
                                <span class="badge bg-danger" style="font-size: 13px">Chưa được duyệt</span>
                            {% elseif purchaseOrder.getStatus() == 1 %}
                                <span class="badge bg-success" style="font-size: 13px">Đã được duyệt</span>
                            {% endif %}
                        </td>
                        <td>
                            x{{ purchaseOrder.getQuantity() }}
                        </td>
                        <td>
                            <span style="color: red;">{{ purchaseOrder.getPrice()|number_format(0, ',', '.') }}₫ </span>
                        </td>
                        <td>
                            {{ address.user.getUsername() }}
                        </td>
                        <td>
                            {{ address.user.getPhone() }}
                        </td>
                        <td>
                            {{ address.street }}, {{ address.ward }}, {{ address.district }}, {{ address.province }}
                        </td>
                        <td>
                            {{ purchaseOrder.getDate()|date('d/m/Y H:i:s') }}
                        </td>
                        {#                    <td class="align-middle text-center"></td>#}
                    </tr>
                {% endif %}
            {% endfor %}
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/dashboard/dashboard_category_create.html.twig
{% extends 'dashboard/base.html.twig' %}

{% block content %}
    <br>
    <div class="container">
    <div class="col-md-10" style="background: white">
        <ul class="list-group">
            <li class="list-group-item" style="background-color: #505050"><h2 style="color: white; text-align: center">Create Category</h2></li>
            <li class="list-group-item">
                {{ form_start(form) }}
                <div class="form-group">
                    <label for="CatName"><strong>Name:</strong></label>
                    {{ form_widget(form.CatName,{
                        'attr':{
                            'class':'form-control'

                        }
                    }) }}
                    <div class="form-group">
                        <label for="due_date">Image</label>
                        {{ form_widget(form.logoImage,{

                        }) }}
                    </div><br>
                    <input type="submit" name="create_category" value="Success" class="btn btn-success btn btn-primary" style="float: right"/>
                    {{ form_end(form) }}
            </li>

        </ul>
    </div>
    </div>
{% endblock %}

templates/dashboard/dashboard_category_details.html.twig
{% extends 'dashboard/base.html.twig' %}

{% block content %}
    <br>
    <div class="container">
    <div class="col-md-10" style="background: white">
        <table class="table">
            <thead>
            <tr>
                <th class="text-center ">Category</th>
                <th class="text-center ">Action</th>
            </tr>
            </thead>
            <tbody>
            {% for category in categories|reverse %}
                <tr>
                    <td class="col-10">
                        <img src="{{ asset('uploads/image/' ~ category.logo) }}" width="70" alt="category image">&emsp;&emsp;
                        {{ category.catname }}
                    </td>
                    <td class="align-middle text-center col-2">
                        <div class="row">
                        <a href="{{path('dashboard_category_edit',{'id':category.id})}} " class='nav-link button button1' style="border:2px solid MediumSeaGreen;text-align: center">Edit</a>&emsp;
                        <a href="{{ path('dashboard_category_delete', {'id': category.id}) }} "class='nav-link button button3' style="border:2px solid Red;text-align: center">Delete</a>
                        </div>
                    </td>
                    <td class="align-middle text-center"></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    </div>
    <style>
        .button {
            /* Green */
            border: none;
            border-radius: 7px;
            transition-duration: 0.4s;
            cursor: pointer;
        }

        .button1 {
            width: 60px;
            color: #28B463;
            border: 2px solid #28B463;
        }

        .button1:hover {
            background-color: #28B463;
            color: white;
        }

        .button3 {
            width: 60px;
            color: #CB4335;
            border: 2px solid #CB4335;
        }

        .button3:hover {
            background-color: #CB4335;
            color: white;
        }

    </style>
{% endblock %}

templates/dashboard/dashboard_category_edit.html.twig
{% extends 'dashboard/base.html.twig' %}

{% block content %}
    <br>
    <div class="container">
        <div class="col-md-10" style="background: white">
            <ul class="list-group">
                <li class="list-group-item" style="background-color: #505050"><h2 style="color: white; text-align: center">Edit Category</h2></li>
                <li class="list-group-item">
                    {{ form_start(form) }}
                    <div class="form-group">
                        <label for="CatName"><strong>Name:</strong></label>
                        {{ form_widget(form.CatName,{
                            'attr':{
                                'class':'form-control'

                            }
                        }) }}
                        <div class="form-group">
                            <label for="due_date">Image</label>
                            {{ form_widget(form.logoImage,{

                            }) }}
                        </div><br>
                        <input type="submit" name="edit_category" value="Success" class="btn btn-success btn btn-primary" style="float: right"/>
                        {{ form_end(form) }}
                </li>

            </ul>
        </div>
    </div>
{% endblock %}

templates/dashboard/dashboard_product_create.html.twig
{% extends 'dashboard/base.html.twig' %}

{% block content %}
<br>
<div class="container">
    <div class="col-md-10" style="background: white">
        <ul class="list-group">
            <li class="list-group-item" style="background-color: #505050"><h2 style="color: white; text-align: center">Create Product</h2></li>
            <li class="list-group-item">
                {{ form_start(form) }}
                <div class="form-group">
                    <label for="category"><strong>Category</strong></label>
                    {{ form_widget(form.category,{
                        'attr':{
                            'class':'form-control'
                        }
                    }) }}
                </div>
                <div class="form-group">
                    <label for="category"><strong>Product Name:</strong></label>
                    {{ form_widget(form.name,{
                        'attr':{
                            'class':'form-control',
                        }
                    }) }}
                </div>
                <div class="form-group">
                    <label for="category"><strong>Nhân vật:</strong></label>
                    {{ form_widget(form.figure,{
                        'attr':{
                            'class':'form-control',
                        }
                    }) }}
                </div>
                <div class="form-group">
                    <label for="category"><strong>Series:</strong></label>
                    {{ form_widget(form.series,{
                        'attr':{
                            'class':'form-control',
                        }
                    }) }}
                </div>
                <div class="form-group">
                    <label for="category"><strong>Hãng sản xuất:</strong></label>
                    {{ form_widget(form.trademark,{
                        'attr':{
                            'class':'form-control',
                        }
                    }) }}
                </div>
                <div class="form-group">
                    <label for="description"><strong>Kích thước:</strong></label>
                    {{ form_widget(form.size,{
                        'attr':{
                            'class':'form-control',
                        }
                    }) }}
                </div>
                <div class="form-group">
                    <label for="category"><strong>Price:</strong></label>
                    {{ form_widget(form.price,{
                        'attr':{
                            'class':'form-control',
                        }
                    }) }}
                </div>
                <div class="form-group">
                    <label for="category"><strong>Quantity:</strong></label>
                    {{ form_widget(form.quantity,{
                        'attr':{
                            'class':'form-control',
                        }
                    }) }}
                </div>
                <div class="form-group">
                    <label for="description"><strong>Description:</strong></label>
                    {{ form_widget(form.description,{
                        'attr':{
                            'class':'form-control',
                        }
                    }) }}
                </div>

                <div class="form-group">
                    <label for="due_date"><strong>Date</strong></label>
                    {{ form_widget(form.date,{
                        'attr':{
                            'class':'form-control'
                        }
                    }) }}
                </div><hr>
                <div class="form-group">
                    <label for="due_date">Image</label>
                    {{ form_widget(form.productImage,{

                    }) }}
                </div>
                <input type="submit" name="create_product" value="Success" class="btn btn-success btn btn-primary" style="float: right"/>
                {{ form_end(form) }}
            </li>
        </ul>
    </div>
</div>
{% endblock %}

templates/dashboard/dashboard_product_edit.html.twig
{% extends 'dashboard/base.html.twig' %}

{% block content %}
<br>
<div class="container">
    <div class="col-md-10" style="background: white">
        <ul class="list-group">
            <li class="list-group-item" style="background-color: #505050"><h2 style="color: white; text-align: center">Edit Product</h2></li>
            <li class="list-group-item">
                {{ form_start(form) }}
                <div class="form-group">
                    <label for="category"><strong>Category</strong></label>
                    {{ form_widget(form.category,{
                        'attr':{
                            'class':'form-control'
                        }
                    }) }}
                </div>
                <div class="form-group">
                    <label for="category"><strong>Product Name:</strong></label>
                    {{ form_widget(form.name,{
                        'attr':{
                            'class':'form-control',
                            'placeholder': 'Product name'
                        }
                    }) }}
                </div>
                <div class="form-group">
                    <label for="category"><strong>Nhân vật:</strong></label>
                    {{ form_widget(form.figure,{
                        'attr':{
                            'class':'form-control',
                        }
                    }) }}
                </div>
                <div class="form-group">
                    <label for="category"><strong>Series:</strong></label>
                    {{ form_widget(form.series,{
                        'attr':{
                            'class':'form-control',
                        }
                    }) }}
                </div>
                <div class="form-group">
                    <label for="category"><strong>Hãng sản xuất:</strong></label>
                    {{ form_widget(form.trademark,{
                        'attr':{
                            'class':'form-control',
                        }
                    }) }}
                </div>
                <div class="form-group">
                    <label for="description"><strong>Kích thước:</strong></label>
                    {{ form_widget(form.size,{
                        'attr':{
                            'class':'form-control',
                        }
                    }) }}
                </div>
                <div class="form-group">
                    <label for="category"><strong>Price:</strong></label>
                    {{ form_widget(form.price,{
                        'attr':{
                            'class':'form-control',
                            'placeholder': 'Price'
                        }
                    }) }}
                </div>
                <div class="form-group">
                    <label for="category"><strong>Quantity:</strong></label>
                    {{ form_widget(form.quantity,{
                        'attr':{
                            'class':'form-control',
                            'placeholder': 'Quantity'
                        }
                    }) }}
                </div>
                <div class="form-group">
                    <label for="description"><strong>Description:</strong></label>
                    {{ form_row(form.description, {
                        'attr': {
                            'cols': 30,
                            'rows': 7,
                            'name': 'description',
                            'class': 'form-control',
                            'placeholder': 'Description'
                        }
                    }) }}

                </div>

                <div class="form-group">
                    <label for="due_date"><strong>Date</strong></label>
                    {{ form_widget(form.date,{
                        'attr':{
                            'class':'form-control'
                        }
                    }) }}
                </div>
                <div class="form-group">
                    <label for="due_date">Image</label>
                    {{ form_widget(form.productImage,{

                    }) }}
                </div>
                <input type="submit" name="edit_product" value="Success" class="btn btn-success btn btn-primary btn-lg" style="float: right"/>

                {{ form_end(form) }}
            </li>
        </ul>
    </div>
</div>
{% endblock %}